# Generated by Django 5.0.7 on 2024-08-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0003_curso_descripcion_curso_fecha_fin_curso_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
